//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrRobotiq
{
    [Serializable]
    public class UR3eGripperMsg : Message
    {
        public const string k_RosMessageName = "ur_robotiq/UR3eGripper";
        public override string RosMessageName => k_RosMessageName;

        public double gripper;

        public UR3eGripperMsg()
        {
            this.gripper = 0.0;
        }

        public UR3eGripperMsg(double gripper)
        {
            this.gripper = gripper;
        }

        public static UR3eGripperMsg Deserialize(MessageDeserializer deserializer) => new UR3eGripperMsg(deserializer);

        private UR3eGripperMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.gripper);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.gripper);
        }

        public override string ToString()
        {
            return "UR3eGripperMsg: " +
            "\ngripper: " + gripper.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
